pub mod frame;
pub mod palette;

#[cfg(test)]
use crate::ppu::NesPPU;
use frame::Frame;

#[cfg(test)]
#[derive(Clone, Copy)]
struct SpritePixel {
    color: (u8, u8, u8),
    behind_background: bool,
    sprite_zero: bool,
}

#[cfg(test)]
#[derive(Clone, Copy)]
struct BackgroundTile {
    lo: u8,
    hi: u8,
    palette: u8,
}

// Render one visible scanline from the PPU's current loopy address. `v` already
// carries coarse X/Y, nametable selection and fine Y for this line; `x` carries
// fine X. This deliberately derives each pixel from that state rather than
// stitching two cached nametable rectangles, so horizontal and vertical wraps
// work together in all four logical nametables.
//
// This reference compositor exists only for focused tests. Production output
// is generated by the PPU's dot pipeline.
#[cfg(test)]
fn render_scanline_reference(ppu: &NesPPU, frame: &mut Frame, line: usize) -> bool {
    render_scanline_reference_with_sprite_zero(ppu, frame, line).is_some()
}

// Return the first sprite-0/background overlap for reference-test scenes.
#[cfg(test)]
fn render_scanline_reference_with_sprite_zero(
    ppu: &NesPPU,
    frame: &mut Frame,
    line: usize,
) -> Option<usize> {
    let (v, fine_x) = ppu.render_scroll();
    let backdrop = palette_color(ppu, ppu.palette_table[0]);
    let mut background_opaque = [false; 256];
    let background_enabled = ppu.mask.show_background();

    // Fine X means a scanline spans at most 33 source tiles. Fetch each tile
    // once, rather than re-reading its two CHR bitplanes for every one of its
    // eight pixels. This removes roughly 120,000 mapper reads per frame.
    let mut tiles = [
        BackgroundTile {
            lo: 0,
            hi: 0,
            palette: 0,
        };
        33
    ];
    if background_enabled {
        for (offset, tile) in tiles.iter_mut().enumerate() {
            *tile = background_tile(ppu, v, offset);
        }
    }

    for x in 0..256 {
        let (color, opaque) = if background_enabled
            && (x >= 8 || ppu.mask.leftmost_8pxl_background())
        {
            let pixel = fine_x as usize + x;
            let tile = tiles[pixel / 8];
            let bit = 7 - (pixel & 0x07);
            let value = ((tile.hi >> bit) & 1) << 1 | ((tile.lo >> bit) & 1);
            if value == 0 {
                (backdrop, false)
            } else {
                let index = 1 + tile.palette as usize * 4 + (value - 1) as usize;
                (palette_color(ppu, ppu.palette_table[index]), true)
            }
        } else {
            (backdrop, false)
        };
        frame.set_pixel(x, line, color);
        background_opaque[x] = opaque;
    }

    if !ppu.mask.show_sprites() {
        return None;
    }

    // Sprite evaluation is ordered by OAM index: the first opaque sprite at a
    // screen pixel wins, even when it has "behind background" priority. Only
    // the first eight sprites on a line participate, matching the PPU limit.
    let mut sprite_pixels = [None; 256];
    let mut selected = 0;
    let mut sprite_zero_hit = None;
    let height = if ppu.ctrl.sprite_size_16() { 16 } else { 8 };

    for sprite in 0..64 {
        let i = sprite * 4;
        // OAM stores one less than the on-screen Y coordinate. Do not wrap
        // $FF to row 0: games use $FF to keep unused sprites off screen.
        let sprite_y = ppu.oam_data[i] as usize + 1;
        if line < sprite_y || line >= sprite_y + height {
            continue;
        }
        let row = line - sprite_y;
        selected += 1;
        if selected > 8 {
            break;
        }

        let attr = ppu.oam_data[i + 2];
        let source_row = if attr & 0x80 != 0 { height - 1 - row } else { row };
        let tile = ppu.oam_data[i + 1];
        let (tile_index, tile_row, bank) = if height == 16 {
            (
                (tile & 0xfe).wrapping_add((source_row / 8) as u8),
                source_row % 8,
                if tile & 1 != 0 { 0x1000 } else { 0 },
            )
        } else {
            (tile, source_row, ppu.ctrl.sprt_pattern_addr())
        };
        let base = bank + tile_index as u16 * 16 + tile_row as u16;
        let (lo, hi) = ppu_pattern_pair(ppu, base);
        let sprite_x = ppu.oam_data[i + 3] as usize;

        for col in 0..8 {
            let x = sprite_x + col;
            if x >= 256 || (x < 8 && !ppu.mask.leftmost_8pxl_sprite()) || sprite_pixels[x].is_some() {
                continue;
            }
            let bit = if attr & 0x40 != 0 { col } else { 7 - col };
            let value = ((hi >> bit) & 1) << 1 | ((lo >> bit) & 1);
            if value == 0 {
                continue;
            }

            let palette_index = 0x11 + ((attr & 0x03) as usize) * 4 + (value - 1) as usize;
            sprite_pixels[x] = Some(SpritePixel {
                color: palette_color(ppu, ppu.palette_table[palette_index]),
                behind_background: attr & 0x20 != 0,
                sprite_zero: sprite == 0,
            });
        }
    }

    for x in 0..256 {
        if let Some(sprite) = sprite_pixels[x] {
            if sprite.sprite_zero && background_opaque[x] && x < 255 && sprite_zero_hit.is_none() {
                sprite_zero_hit = Some(x);
            }
            if !sprite.behind_background || !background_opaque[x] {
                frame.set_pixel(x, line, sprite.color);
            }
        }
    }
    sprite_zero_hit
}

#[cfg(test)]
fn background_tile(ppu: &NesPPU, v: u16, tile_offset: usize) -> BackgroundTile {
    let mut coarse_x = (v & 0x001f) as usize + tile_offset;
    let mut nametable = ((v >> 10) & 0x03) as u16;
    if coarse_x >= 32 {
        coarse_x -= 32;
        nametable ^= 0x01;
    }

    let coarse_y = ((v >> 5) & 0x001f) as usize;
    let fine_y = ((v >> 12) & 0x07) as u16;
    let nametable_base = 0x2000 | (nametable << 10);
    let tile_addr = nametable_base + (coarse_y * 32 + coarse_x) as u16;
    let tile = nametable_byte(ppu, tile_addr);
    let (lo, hi) = ppu_pattern_pair(ppu, ppu.ctrl.bknd_pattern_addr() + tile as u16 * 16 + fine_y);
    let attr_addr = nametable_base + 0x03c0 + ((coarse_y / 4) * 8 + coarse_x / 4) as u16;
    let attr = nametable_byte(ppu, attr_addr);
    let shift = ((coarse_y & 0x02) << 1) | (coarse_x & 0x02);
    BackgroundTile {
        lo,
        hi,
        palette: (attr >> shift) & 0x03,
    }
}

#[cfg(test)]
fn nametable_byte(ppu: &NesPPU, addr: u16) -> u8 {
    ppu.vram[ppu.mirror_vram_addr(addr) as usize]
}

#[cfg(test)]
fn ppu_pattern_pair(ppu: &NesPPU, addr: u16) -> (u8, u8) {
    let mut mapper = ppu.mapper.borrow_mut();
    (mapper.ppu_read(addr), mapper.ppu_read(addr + 8))
}

#[cfg(test)]
fn palette_color(ppu: &NesPPU, value: u8) -> (u8, u8, u8) {
    let _ = ppu;
    palette::SYSTEM_PALLETE[(value & 0x3f) as usize]
}

// Ch6.3 tile viewer: decode a single CHR tile into a Frame. This is a debug
// helper used by the UI and intentionally remains independent of PPU state.
pub fn show_tile(chr_rom: &Vec<u8>, bank: usize, tile_n: usize) -> Frame {
    assert!(bank <= 1);
    let mut frame = Frame::new();
    let base = bank * 0x1000 + tile_n * 16;
    let tile = &chr_rom[base..base + 16];
    for y in 0..8 {
        for x in 0..8 {
            let bit = 7 - x;
            let value = ((tile[y + 8] >> bit) & 1) << 1 | ((tile[y] >> bit) & 1);
            let color = match value {
                0 => palette::SYSTEM_PALLETE[0x01],
                1 => palette::SYSTEM_PALLETE[0x23],
                2 => palette::SYSTEM_PALLETE[0x27],
                _ => palette::SYSTEM_PALLETE[0x30],
            };
            frame.set_pixel(x, y, color);
        }
    }
    frame
}

#[cfg(test)]
mod test {
    use super::*;
    use crate::cartridge::Mirroring;

    fn scene() -> NesPPU {
        let mut chr = vec![0; 0x2000];
        chr[16] = 0xff;
        let mut ppu = NesPPU::new(crate::mapper::test_nrom(chr, Mirroring::Vertical));
        ppu.vram[0] = 1;
        ppu.vram[1] = 1;
        ppu.palette_table[0] = 0x0f;
        ppu.palette_table[1] = 0x21;
        ppu
    }

    fn assert_pixel(frame: &Frame, x: usize, y: usize, color: (u8, u8, u8)) {
        let offset = (y * 256 + x) * 3;
        assert_eq!(
            &frame.data[offset..offset + 3],
            &[color.0, color.1, color.2],
            "pixel ({x}, {y})"
        );
    }

    #[test]
    fn background_obeys_mask_and_left_edge_clip() {
        let mut ppu = scene();
        let mut frame = Frame::new();
        render_scanline_reference(&ppu, &mut frame, 0);
        assert_pixel(&frame, 0, 0, palette::SYSTEM_PALLETE[0x0f]);

        ppu.write_to_mask(0b0000_1000);
        render_scanline_reference(&ppu, &mut frame, 0);
        assert_pixel(&frame, 0, 0, palette::SYSTEM_PALLETE[0x0f]);
        assert_pixel(&frame, 8, 0, palette::SYSTEM_PALLETE[0x21]);

        ppu.write_to_mask(0b0000_1010);
        render_scanline_reference(&ppu, &mut frame, 0);
        assert_pixel(&frame, 0, 0, palette::SYSTEM_PALLETE[0x21]);
    }

    #[test]
    fn sprites_use_oam_y_plus_one_and_background_priority() {
        let mut ppu = scene();
        ppu.write_to_mask(0b0001_1110);
        ppu.palette_table[0x11] = 0x30;
        // Sprite 0 is one row below OAM Y and is behind a solid background.
        ppu.oam_data[0..4].copy_from_slice(&[0, 1, 0x20, 8]);
        let mut frame = Frame::new();

        assert!(!render_scanline_reference(&ppu, &mut frame, 0));
        assert!(render_scanline_reference(&ppu, &mut frame, 1));
        assert_pixel(&frame, 8, 1, palette::SYSTEM_PALLETE[0x21]);
    }

    #[test]
    fn fine_x_scroll_advances_to_the_next_tile_at_the_right_pixel() {
        let mut ppu = scene();
        ppu.write_to_mask(0b0000_1010);
        ppu.mapper.borrow_mut().ppu_write(16, 0x80);
        ppu.write_to_scroll(1);
        ppu.write_to_scroll(0);
        ppu.sync_scroll_for_test();
        let mut frame = Frame::new();
        render_scanline_reference(&ppu, &mut frame, 0);

        // Tile 1 only has bit 7 set: fine X 1 makes pixel 0 transparent, and
        // pixel 7 begins the next tile (also tile 1 in this scene).
        assert_pixel(&frame, 0, 0, palette::SYSTEM_PALLETE[0x0f]);
        assert_pixel(&frame, 7, 0, palette::SYSTEM_PALLETE[0x21]);
    }

    #[test]
    fn coarse_x_wrap_reads_the_adjacent_logical_nametable() {
        let mut ppu = scene();
        ppu.write_to_mask(0b0000_1010);
        ppu.vram[31] = 1;
        ppu.vram[0x400] = 2;
        ppu.mapper.borrow_mut().ppu_write(40, 0xff); // tile 2, high plane
        ppu.palette_table[2] = 0x22;
        ppu.write_to_scroll(0xf8); // nametable 0, coarse X 31
        ppu.write_to_scroll(0);
        ppu.sync_scroll_for_test();
        assert_eq!(ppu.render_scroll(), (0x001f, 0));
        let mut frame = Frame::new();
        render_scanline_reference(&ppu, &mut frame, 0);

        assert_pixel(&frame, 0, 0, palette::SYSTEM_PALLETE[0x21]);
        assert_pixel(&frame, 8, 0, palette::SYSTEM_PALLETE[0x22]);
    }

    #[test]
    fn sprites_support_8_by_16_tiles() {
        let mut ppu = scene();
        ppu.write_to_ctrl(0b0010_0000); // 8x16 sprites
        ppu.write_to_mask(0b0001_0100);
        ppu.palette_table[0x11] = 0x30;
        // Tile 1 is the lower half of the 8x16 sprite and is opaque.
        ppu.oam_data[0..4].copy_from_slice(&[0, 0, 0, 8]);
        let mut frame = Frame::new();
        render_scanline_reference(&ppu, &mut frame, 9);

        assert_pixel(&frame, 8, 9, palette::SYSTEM_PALLETE[0x30]);
    }

    #[test]
    fn only_the_first_eight_sprites_on_a_line_are_rendered() {
        let mut ppu = scene();
        ppu.write_to_mask(0b0001_0100);
        ppu.palette_table[0x11] = 0x30;
        // The first eight candidates are transparent; sprite 8 would be
        // visible if evaluation did not stop at the hardware's eight-sprite
        // limit.
        for sprite in 0..8 {
            ppu.oam_data[sprite * 4..sprite * 4 + 4].copy_from_slice(&[0, 0, 0, 8]);
        }
        ppu.oam_data[8 * 4..8 * 4 + 4].copy_from_slice(&[0, 1, 0, 8]);
        let mut frame = Frame::new();
        render_scanline_reference(&ppu, &mut frame, 1);

        assert_pixel(&frame, 8, 1, palette::SYSTEM_PALLETE[0x0f]);
    }

    #[test]
    fn oam_y_ff_keeps_an_unused_sprite_off_screen() {
        let mut ppu = scene();
        ppu.write_to_mask(0b0001_0100);
        ppu.palette_table[0x11] = 0x30;
        ppu.oam_data[0..4].copy_from_slice(&[0xff, 1, 0, 8]);
        let mut frame = Frame::new();
        render_scanline_reference(&ppu, &mut frame, 0);

        assert_pixel(&frame, 8, 0, palette::SYSTEM_PALLETE[0x0f]);
    }
}
